# Generated by Django 4.1 on 2022-09-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_name', models.CharField(max_length=30)),
                ('link_to_presentation', models.URLField()),
                ('champion_icon', models.ImageField(upload_to='champion/icon/')),
                ('current_patch', models.CharField(max_length=15)),
            ],
        ),
    ]
