# Generated by Django 4.1 on 2022-09-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0002_champion_champion_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='champion_desc',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='champion',
            name='link_to_presentation',
            field=models.URLField(null=True),
        ),
    ]
