# Generated by Django 4.1 on 2023-02-15 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main_website", "0003_alter_champion_champion_desc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallVideos",
            fields=[
                (
                    "chall_videos_id",
                    models.AutoField(
                        db_column="CHALL_VIDEOS_ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "chall_name",
                    models.CharField(
                        blank=True, db_column="CHALL_NAME", max_length=30, null=True
                    ),
                ),
                (
                    "chall_link",
                    models.URLField(blank=True, db_column="CHALL_LINK", null=True),
                ),
            ],
            options={
                "db_table": "chall_videos",
            },
        ),
        migrations.CreateModel(
            name="Champions",
            fields=[
                (
                    "champion_id",
                    models.AutoField(
                        db_column="CHAMPION_ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "champion_tier",
                    models.CharField(
                        blank=True, db_column="CHAMPION_TIER", max_length=15, null=True
                    ),
                ),
                (
                    "champion_name",
                    models.CharField(db_column="CHAMPION_NAME", max_length=25),
                ),
                (
                    "champion_icon",
                    models.ImageField(
                        blank=True,
                        db_column="CHAMPION_ICON",
                        null=True,
                        upload_to="champion/icon/",
                    ),
                ),
                (
                    "champion_story",
                    models.TextField(blank=True, db_column="CHAMPION_STORY", null=True),
                ),
                (
                    "users_favourite",
                    models.ManyToManyField(to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "db_table": "champions",
            },
        ),
        migrations.CreateModel(
            name="ChampionsPresentations",
            fields=[
                (
                    "presentation_link",
                    models.URLField(
                        blank=True, db_column="PRESENTATION_LINK", null=True
                    ),
                ),
                (
                    "presentation_version",
                    models.CharField(
                        blank=True,
                        db_column="PRESENTATION_VERSION",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "champions_presentations_id",
                    models.AutoField(
                        db_column="CHAMPIONS_PRESENTATIONS_ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "champion",
                    models.ForeignKey(
                        blank=True,
                        db_column="CHAMPION_ID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="main_website.champions",
                    ),
                ),
            ],
            options={
                "db_table": "champions_presentations",
            },
        ),
        migrations.CreateModel(
            name="ChampionsSkills",
            fields=[
                (
                    "skills_id",
                    models.IntegerField(
                        db_column="SKILLS_ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "skill_name",
                    models.CharField(
                        blank=True, db_column="SKILL_NAME", max_length=40, null=True
                    ),
                ),
                (
                    "skill_type",
                    models.CharField(
                        blank=True, db_column="SKILL_TYPE", max_length=15, null=True
                    ),
                ),
                (
                    "skill_cooldown",
                    models.CharField(
                        blank=True, db_column="SKILL_COOLDOWN", max_length=30, null=True
                    ),
                ),
                (
                    "skill_cost",
                    models.CharField(
                        blank=True, db_column="SKILL_COST", max_length=30, null=True
                    ),
                ),
                (
                    "skill_range",
                    models.IntegerField(blank=True, db_column="SKILL_RANGE", null=True),
                ),
                (
                    "skill_description",
                    models.TextField(
                        blank=True, db_column="SKILL_DESCRIPTION", null=True
                    ),
                ),
                (
                    "skill_icon",
                    models.ImageField(
                        blank=True,
                        db_column="SKILL_ICON",
                        null=True,
                        upload_to="skills/icon/",
                    ),
                ),
                (
                    "champion",
                    models.ForeignKey(
                        blank=True,
                        db_column="CHAMPION_ID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="main_website.champions",
                    ),
                ),
            ],
            options={
                "db_table": "champions_skills",
            },
        ),
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "item_id",
                    models.IntegerField(
                        db_column="ITEM_ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        blank=True, db_column="ITEM_NAME", max_length=30, null=True
                    ),
                ),
                (
                    "item_cost",
                    models.IntegerField(blank=True, db_column="ITEM_COST", null=True),
                ),
                (
                    "item_description",
                    models.TextField(
                        blank=True, db_column="ITEM_DESCRIPTION", null=True
                    ),
                ),
                (
                    "item_icon",
                    models.ImageField(
                        blank=True,
                        db_column="ITEM_ICON",
                        null=True,
                        upload_to="items/icon/",
                    ),
                ),
                ("champions", models.ManyToManyField(to="main_website.champions")),
            ],
            options={
                "db_table": "items",
            },
        ),
        migrations.CreateModel(
            name="Runes",
            fields=[
                (
                    "runes_id",
                    models.IntegerField(
                        db_column="RUNES_ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "runes_type",
                    models.CharField(
                        blank=True, db_column="RUNES_TYPE", max_length=30, null=True
                    ),
                ),
                (
                    "rune_name",
                    models.CharField(
                        blank=True, db_column="RUNE_NAME", max_length=30, null=True
                    ),
                ),
                (
                    "rune_description",
                    models.TextField(
                        blank=True, db_column="RUNE_DESCRIPTION", null=True
                    ),
                ),
                (
                    "rune_icon",
                    models.ImageField(
                        blank=True,
                        db_column="RUNE_ICON",
                        null=True,
                        upload_to="runes/icon/",
                    ),
                ),
                ("champions", models.ManyToManyField(to="main_website.champions")),
            ],
            options={
                "db_table": "runes",
            },
        ),
        migrations.DeleteModel(
            name="Champion",
        ),
        migrations.AddField(
            model_name="challvideos",
            name="champion",
            field=models.ForeignKey(
                blank=True,
                db_column="CHAMPION_ID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main_website.champions",
            ),
        ),
    ]
