# Generated by Django 4.1 on 2023-02-15 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main_website", "0005_championspresentations_presentation_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="champions",
            name="users_favourite",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="championsskills",
            name="skills_id",
            field=models.AutoField(
                db_column="SKILLS_ID", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="champions",
            field=models.ManyToManyField(blank=True, to="main_website.champions"),
        ),
        migrations.AlterField(
            model_name="items",
            name="item_id",
            field=models.AutoField(
                db_column="ITEM_ID", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="runes",
            name="champions",
            field=models.ManyToManyField(blank=True, to="main_website.champions"),
        ),
        migrations.AlterField(
            model_name="runes",
            name="runes_id",
            field=models.AutoField(
                db_column="RUNES_ID", primary_key=True, serialize=False
            ),
        ),
    ]
