# Generated by Django 4.1 on 2023-03-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_website", "0006_alter_champions_users_favourite_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challvideos",
            name="chall_link",
            field=models.URLField(
                blank=True, db_column="CHALL_LINK", null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="challvideos",
            name="chall_name",
            field=models.CharField(
                blank=True,
                db_column="CHALL_NAME",
                max_length=30,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="champions",
            name="champion_icon",
            field=models.ImageField(
                blank=True,
                db_column="CHAMPION_ICON",
                null=True,
                unique=True,
                upload_to="champion/icon/",
            ),
        ),
        migrations.AlterField(
            model_name="champions",
            name="champion_name",
            field=models.CharField(
                db_column="CHAMPION_NAME", max_length=25, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="championspresentations",
            name="presentation_link",
            field=models.URLField(
                blank=True, db_column="PRESENTATION_LINK", null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="championsskills",
            name="skill_name",
            field=models.CharField(
                blank=True,
                db_column="SKILL_NAME",
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="item_name",
            field=models.CharField(
                blank=True, db_column="ITEM_NAME", max_length=30, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="runes",
            name="rune_name",
            field=models.CharField(
                blank=True, db_column="RUNE_NAME", max_length=30, null=True, unique=True
            ),
        ),
    ]
