# Generated by Django 4.1 on 2023-03-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_website", "0007_alter_challvideos_chall_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="championsskills",
            name="skill_icon",
            field=models.ImageField(
                blank=True,
                db_column="SKILL_ICON",
                null=True,
                unique=True,
                upload_to="skills/icon/",
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="item_icon",
            field=models.ImageField(
                blank=True,
                db_column="ITEM_ICON",
                null=True,
                unique=True,
                upload_to="items/icon/",
            ),
        ),
        migrations.AlterField(
            model_name="runes",
            name="rune_icon",
            field=models.ImageField(
                blank=True,
                db_column="RUNE_ICON",
                null=True,
                unique=True,
                upload_to="runes/icon/",
            ),
        ),
    ]
