# Generated by Django 4.1 on 2023-03-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_website", "0008_alter_championsskills_skill_icon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="champions",
            name="champion_tier",
        ),
        migrations.RemoveField(
            model_name="championsskills",
            name="skill_type",
        ),
    ]
